### ISSUE TITLE
cannot open XML file by name

### ISSUE THREAD

**Issue by smcoll** [valdergallo/data-importer#74]
```
i = MyXMLImporter(source='sample.xml')
i.cleaned_data
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "[...]/lib/python2.7/site-packages/data_importer/importers/base.py", line 268, in cleaned_data
    for data in self._read_file():
  File "[...]/lib/python2.7/site-packages/data_importer/importers/base.py", line 321, in _read_file
    for row, values in enumerate(reader, 1):
  File "[...]/lib/python2.7/site-packages/data_importer/readers/xml_reader.py", line 13, in read
    tree = et.fromstring(self.instance.source)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    return parser.close()
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1654, in close
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
```

This is, in part, because `BaseImporter` [only allows files with the `csv` extention](https://github.com/valdergallo/data-importer/blob/2.3.0/data_importer/importers/base.py#L79) to be opened that way.

Still debugging; i think there are other issues as well...

**Comment by smcoll** [comment]
my vote is to move that 'csv' into a `valid_extensions` property (as a list) which could be implemented in each subclass.

**Comment by smcoll** [comment]
Since the `XMLReader` is expecting a string, i had to do something like this in my workaround subclass:

```
if isinstance(source, str) and os.path.exists(source) and source.endswith('xml'):
    self._source = open(source, 'rb').read()
```
