### ISSUE TITLE
Invalid Syntax error in data_importer/importers/base.py

### ISSUE THREAD

**Issue by Frikster** [valdergallo/data-importer#76]
Hi,

I'm afraid I cannot explain the following error. The line of code that causes the error is simply 
    
    from data_importer.importers import CSVImporter
which I took from the documentation

    manage.py@minimal-django-file-upload-example > runserver 8000
    bash -cl "/usr/bin/python3.4 /home/cornelis/pycharm-5.0.3/helpers/pycharm/django_manage.py runserver 8000 /home/cornelis/PycharmProjects/minimal-django-file-upload-example/src/for_django_1-8/myproject"
    Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f1d5be71950>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
      File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
      File "/usr/local/lib/python3.4/dist-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
      File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
      File "/usr/local/lib/python3.4/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
      File "/usr/local/lib/python3.4/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
      File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
      File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "<frozen importlib._bootstrap>", line 1448, in exec_module
      File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
      File "/home/cornelis/PycharmProjects/minimal-django-file-upload-example/src/for_django_1-8/myproject/myproject/myapp/models.py", line 3, in <module>
    from data_importer.importers import CSVImporter
      File "/usr/local/lib/python3.4/dist-packages/data_importer/importers/__init__.py", line 1, in <module>
    from data_importer.importers.base import *
      File "/usr/local/lib/python3.4/dist-packages/data_importer/importers/base.py", line 200
    except StopImporter, e:
                       ^
    SyntaxError: invalid syntax'

**Comment by valdergallo** [comment]
In python3.4 exceptions need be write as (except StopImporter as e)
But, I need migrate all the project to Python 3.4, is one issue that I need do ...

**Comment by paolodina** [comment]
I tried the importer with Python 3.4 and Django 1.9 and it works without any problem (last commit).

**Comment by valdergallo** [comment]
fixed in the last version
