### ISSUE TITLE
ImportError: No module named 'default_settings'

### ISSUE THREAD

**Issue by mbonnet** [valdergallo/data-importer#79]
i've got this error when i want to import XMLImport (python 3.5 with django) :
>>> from data_importer.importers import XMLImporter

Traceback (most recent call last):
  File "C:\Users\A526419\AppData\Local\Programs\Python\Python35\lib\site-package
s\django-1.9.2-py3.5.egg\django\core\management\commands\shell.py", line 69, in
handle
    self.run_shell(shell=options['interface'])
  File "C:\Users\A526419\AppData\Local\Programs\Python\Python35\lib\site-package
s\django-1.9.2-py3.5.egg\django\core\management\commands\shell.py", line 61, in
run_shell
    raise ImportError
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\A526419\AppData\Local\Programs\Python\Python35\lib\site-package
s\data_importer\importers\__init__.py", line 1, in <module>
    from data_importer.importers.base import *
  File "C:\Users\A526419\AppData\Local\Programs\Python\Python35\lib\site-package
s\data_importer\importers\base.py", line 9, in <module>
    from django.utils.encoding import force_unicode
ImportError: cannot import name 'force_unicode'
>>> from data_importer.importers import XMLImporter
Traceback (most recent call last):
  File "C:\Users\A526419\AppData\Local\Programs\Python\Python35\lib\site-package
s\django-1.9.2-py3.5.egg\django\core\management\commands\shell.py", line 69, in
handle
    self.run_shell(shell=options['interface'])
  File "C:\Users\A526419\AppData\Local\Programs\Python\Python35\lib\site-package
s\django-1.9.2-py3.5.egg\django\core\management\commands\shell.py", line 61, in
run_shell
    raise ImportError
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\A526419\AppData\Local\Programs\Python\Python35\lib\site-package
s\data_importer\importers\__init__.py", line 1, in <module>
    from data_importer.importers.base import *
  File "C:\Users\A526419\AppData\Local\Programs\Python\Python35\lib\site-package
s\data_importer\importers\base.py", line 12, in <module>
    from data_importer.core.base import objclass2dict
  File "C:\Users\A526419\AppData\Local\Programs\Python\Python35\lib\site-package
s\data_importer\core\base.py", line 2, in <module>
    import default_settings
ImportError: No module named 'default_settings'

**Comment by valdergallo** [comment]
I need port this project to Python 3.5 ... this project is working only in python 2.4, 2.5, 2.6 and 2.7
